services:

  mongodb:
    image: mongo:8.3.7
    
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123

    command: ["mongod", "--auth"]
      
    ports:
      - "27018:27017"
    
    networks :
      - mongo_mig
      
    volumes:
      - mongo_data:/data/db


  migration:
    build: .
      
    environment:
      MONGODB_URI: mongodb://mongodb:27017
      MONGODB_AUTH_DB: Healthcare
      DATABASE_NAME: Healthcare
      COLLECTION_NAME: Patients
    
      CSV_INPUT: /data/healthcare_dataset.csv
      CSV_OUTPUT: /data/healthcare_clean.csv
      CSV_DELIMITER: ","
      CSV_DUPLICATES: /data/doublons_csv.csv
      MONGODB_DUPLICATES: /data/doublons_mongodb.csv
      
      APPLY_CHANGES: "true"
      MAX_EXAMPLES: "10"
      REQUIRE_EMPTY_COLLECTION: "true"

    networks :
      - mongo_mig
      
    volumes:
      - ./healthcare_dataset.csv:/input/healthcare_dataset.csv:ro
      - csv_data:/data

    command: >
      sh -c "cp /input/healthcare_dataset.csv /data/healthcare_dataset.csv
      && python healthcare_migration.py"

    depends_on:
      - mongodb

networks:
  mongo_mig:
    driver : bridge

volumes:
  csv_data:
  mongo_data:
